apiVersion: v1
kind: Service
metadata:
  name: ntf-clusterip-serv
spec:
  selector:
    app: ntf
  ports:
    - name: ntf
      protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
