apiVersion: v1
kind: Service
metadata:
  name: ntf-nodeport
spec:
  selector:
    app: ntf
  ports:
    - name: ntf
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30010
  type: NodePort
