apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntf-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntf
  template:
    metadata:
      labels:
        app: ntf
    spec:
      containers:
        - name: ntf
          image: stefanmijic/notification-service:latest
          ports:
            - containerPort: 3001
