apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a
  template:
    metadata:
      labels:
        app: a
    spec:
      containers:
        - name: a
          image: stefanmijic/authenticationigp:latest
          ports:
            - containerPort: 8080
