apiVersion: v1
kind: Service
metadata:
  name: a-nodeport
spec:
  selector:
    app: a
  ports:
    - name: a
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
